/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_TEST_4BIT_FILES           7
#define MMAP_TEST_4BIT_CHECKSUM        0x5F08

enum MMAP_TEST_4BIT_LISTS {
    MMAP_TEST_4BIT_B0001_SBMP = 0,        /*!< b0001.sbmp */
    MMAP_TEST_4BIT_B0002_SBMP = 1,        /*!< b0002.sbmp */
    MMAP_TEST_4BIT_B0003_SBMP = 2,        /*!< b0003.sbmp */
    MMAP_TEST_4BIT_B0004_SBMP = 3,        /*!< b0004.sbmp */
    MMAP_TEST_4BIT_B0005_SBMP = 4,        /*!< b0005.sbmp */
    MMAP_TEST_4BIT_B0006_SBMP = 5,        /*!< b0006.sbmp */
    MMAP_TEST_4BIT_B0007_SBMP = 6,        /*!< b0007.sbmp */
};
