/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_TEST_8BIT_FILES           10
#define MMAP_TEST_8BIT_CHECKSUM        0x7472

enum MMAP_TEST_8BIT_LISTS {
    MMAP_TEST_8BIT_CONNECTING_0000_SBMP = 0,        /*!< connecting_0000.sbmp */
    MMAP_TEST_8BIT_CONNECTING_0001_SBMP = 1,        /*!< connecting_0001.sbmp */
    MMAP_TEST_8BIT_CONNECTING_0002_SBMP = 2,        /*!< connecting_0002.sbmp */
    MMAP_TEST_8BIT_CONNECTING_0003_SBMP = 3,        /*!< connecting_0003.sbmp */
    MMAP_TEST_8BIT_CONNECTING_0004_SBMP = 4,        /*!< connecting_0004.sbmp */
    MMAP_TEST_8BIT_CONNECTING_0005_SBMP = 5,        /*!< connecting_0005.sbmp */
    MMAP_TEST_8BIT_CONNECTING_0006_SBMP = 6,        /*!< connecting_0006.sbmp */
    MMAP_TEST_8BIT_CONNECTING_0007_SBMP = 7,        /*!< connecting_0007.sbmp */
    MMAP_TEST_8BIT_CONNECTING_0008_SBMP = 8,        /*!< connecting_0008.sbmp */
    MMAP_TEST_8BIT_CONNECTING_0009_SBMP = 9,        /*!< connecting_0009.sbmp */
};
