/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_TEST_8BIT_FILES           3
#define MMAP_TEST_8BIT_CHECKSUM        0x563B

enum MMAP_TEST_8BIT_LISTS {
    MMAP_TEST_8BIT_GIFGIT_AAF = 0,        /*!< gifgit.aaf */
    MMAP_TEST_8BIT_OUTPUT_AAF = 1,        /*!< output.aaf */
    MMAP_TEST_8BIT_WAKE_AAF = 2,        /*!< wake.aaf */
};
